spring.datasource.driverClassName=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/XE
spring.datasource.username=CURSO
spring.datasource.password=CURSO

logging.level.root=error

spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.Oracle10gDialect

spring.jpa.open-in-view=false
spring.jackson.serialization.FAIL_ON_EMPTY_BEANS=false

spring.jooq.sql-dialect=ORACLE

spring.flyway.enabled=false
